language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: WPgBxpk67slKXtD/LOAUsy34nC5M5KS3t/LWnERrhDViujFokfkkrT9qHAaGMcbWYrkE/yzMbyHP5Tx6yQngAI0ZaLajlKdCmH3jmmwTUKKb6zO0h6KBzG92jWVnQaXxO4sHm+UT1P+NBpxw+89OFbUIXSHh4vfrtUF03aSHmxJOYrzAy8HkjPgoX7syW+X6VB6s8J5xShfb9ZaywpfrmpvGCWNfP7qUC7boqVTHDdBp6+HlSHcPK/cGmSjY+3sLPhh21OUjc58QJ5vb76DshWcA1gWcAYGojmWFg6SBu8UwhXhCVZbSVJZ1lIrLBBqQwQcm8Sa7qVXvDHLTt8qljPjLmu/MtXxKslZOa5FfQF3my6TYwTw6m5eojcBx02QA7wOQSnvzu7Cse25uB058HErBc0VWc8kSRXb/rr1PgbSsvhrqIeGjhcQ6cQsvPe8oQjW0EV91jA+LvPJsXhfwC2lcvVlkBj2FlNpyJlMab7MQzdWtrgGf1Pl7U5U4jD+3vrut6vjnYTot34ckKvxO3NNCB+B3BgVlYh64Gp5zymEEnuUMfL18IWakY/dhQkIlwWfI0he8YQFWBZM9VFCgLB94K0XBtpxH9nMOSiNIOrofYRUV5je4egbQRdh3VUwBycKZUhbPm3y3BRNnAbIjHiBUAO/QkvHYKlPHhCvQb50=
  app: arcane-mesa-19587
  on:
    repo: branotto/Dinner-designer
